# Generated by Django 4.1.7 on 2023-04-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0005_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date']},
        ),
    ]
